"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from elasticsearch import Elasticsearch
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-!08qm@gmvvk8=yqb6*5fo+jvca4(a@*ml3=wld^l8f3_pbwb$7'

DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'myapp',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

X_FRAME_OPTIONS = 'ALLOW-FROM https://192.168.0.60'

CSP_FRAME_ANCESTORS = ['https://192.168.0.60',
                       'https://192.168.0.31']

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myapp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'monitoring_db',         
        'USER': 'postgres',         
        'PASSWORD': 'coremax1@#', 
        'HOST': '192.168.0.31',            
        'PORT': '5432',                  
    },
    'mariadb_nova': {  
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'nova',  
        'USER': 'root',  
        'PASSWORD': 'bcyEm8dQ0c43TbsZzWX7HFpn6ddsEmYb7Saiewfw',  
        'HOST': '10.0.2.110', 
        'PORT': '3306',  
    },
    'mariadb_glance': {  
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'glance',  
        'USER': 'root',  
        'PASSWORD': 'bcyEm8dQ0c43TbsZzWX7HFpn6ddsEmYb7Saiewfw',  
        'HOST': '10.0.2.110',  
        'PORT': '3306',  
    },
    'mariadb_neutron': {  
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'neutron', 
        'USER': 'root', 
        'PASSWORD': 'bcyEm8dQ0c43TbsZzWX7HFpn6ddsEmYb7Saiewfw', 
        'HOST': '10.0.2.110',  
        'PORT': '3306', 
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
SECURE_SSL_REDIRECT = True  
SECURE_HSTS_SECONDS = 3600  
SECURE_HSTS_INCLUDE_SUBDOMAINS = True 
SECURE_HSTS_PRELOAD = True 

CORS_ALLOWED_ORIGINS = [
    "https://192.168.0.60",
    "https://192.168.0.31"
]