# Generated by Django 5.1.1 on 2024-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('mem_usage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mem_usage',
                'managed': False,
            },
        ),
    ]
