# Generated by Django 5.1.1 on 2024-09-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_memusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('disk_size', models.IntegerField()),
                ('disk_used', models.IntegerField()),
                ('ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disk_usage',
                'managed': False,
            },
        ),
    ]
